### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by hglaude** [AWehenkel/UMNN#1]
Hello,

Could you please add a license, for example MIT, to make your code reusable?

Best,
Hadrien

**Comment by AWehenkel** [comment]
Dear Hadrien,

Thanks for your  #message. I have just added a GNU GPL v3 license. I hope it will match your expectations.

Best regards,

Antoine

**Comment by hglaude** [comment]
Hello Antoine,

Thank you for addressing the issue. I don't know if it's intended but the GPL v3 license is overly restrictive to be used in companies. If it's not intended would you be willing to switch to something less restrictive like MIT, BSD, Apache.

Thank you for your work,
Hadrien

**Comment by AWehenkel** [comment]
Hi Hadrien,

I have just switched it to BSD3. Hope it fits your need.

All the best,

Antoine

**Comment by hglaude** [comment]
Thank you!
