### ISSUE TITLE
Link to code not in paper pdf

### ISSUE THREAD

**Issue by AustinT** [AWehenkel/UMNN#5]
Hello Antoine, I was just looking at your paper and noticed that the latest arXiv version still says "The source code to reproduce our experiments will be made available on Github at the end of the reviewing process". It might be nice to put the link to this (very nice) repo in the paper so that it's slightly easier to find.

**Comment by AWehenkel** [comment]
Hi Austin, 
Thanks for notifying me! This has been updated.
Regards,
Antoine
