### ISSUE TITLE
Is Lipschitz constraint enforced in the code?

### ISSUE THREAD

**Issue by WenjianHuang93** [AWehenkel/UMNN#7]
I found the function force_lipschitz in the code, but I did not see where it was used. Is this constraint used or really necessary in the codebase?

**Comment by AWehenkel** [comment]
Hi,

The function is not used and not necessary. However, enforcing Lipschtizness may help prevent overfitting in some cases and ensure that the quadrature converges for a small number of integration points.

**Comment by WenjianHuang93** [comment]
I see. Thanks for your reply.
